This plots should be built in the scope of index.Rmd

```{r past_six_months_panel, eval=FALSE}
summ %>%
  filter(key == "Total") %>%
  mutate(Date = as.Date(Date)) %>%
  filter(Date >= key_dates[["this_week"]] - (365 / 2)) %>%
  ggplot() +
  geom_line(aes(Date, value), size = 1.2) +
  scale_y_continuous(breaks = pretty_breaks(2),
                     expand = expand_scale()) +
  scale_x_date(breaks = pretty_breaks(6),
               labels = function(x) format(x, "%b %Y"),
               expand = expand_scale()) +
  labs(x = NULL, y = NULL) +
  blg_theme_default(12) +
  theme(plot.title  = element_text(size = 12, hjust = -0.052),
        axis.text.y = element_text(),
        panel.grid.major.x = element_blank())
```

```{r plot_no_growth_weeks, eval=FALSE}
# Which basins have had the fewest "no growth" weeks?
x <- map(unique(rc_basin$basin), ~{
    rc_basin %>%
        filter(basin == .x & key == "Total") %>%
        mutate(change = value - lag(value, 1L)) %>%
        filter(!is.na(change)) %>%
        filter(change < 1) %>%
        filter(lubridate::year(Date) == 2017L)
           }) %>%
  map_int(nrow)

y <- tibble(Basin = unique(rc_basin$basin), Weeks = x)

y %>%
    arrange(Weeks) %>%
    mutate(Basin = factor(Basin, levels = rev(Basin))) %>%
    ggplot() +
    geom_col(aes(Basin, Weeks, fill = Weeks)) +
    geom_text(aes(Basin, Weeks, label = Weeks), nudge_y = 1.7) +
    coord_flip() +
    guides(fill = FALSE) +
    labs(title = "Top Performers",
         subtitle = paste0("Which basins have had the fewest", "\nno-growth weeks during 2017?"),
         x = NULL)
```
