---
title  : "US Rig Counts: Miscellaneous"
author : "Luke Smith"
date   : "2017-10-06"
tags   : [r, oil, gas, oil and gas, rig counts]
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : "US Rig Counts"
  description : ""
  image       : ""
og :
  image : ""
---

```{r setup_lib_std, include=FALSE}
# ---- Library_Tidyverse_Setup
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)

# ---- My_Blogging_Setup
library(blg)
```

```{r knitr_opts_chunk_std, include=FALSE}
# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r knitr_opts_hooks_std, include=FALSE}
# ---- knitr_Options_Setup
orig_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")

# ---- Hooks_Setup
knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

old_inline <- knit_hooks$get("inline")
```

```{r r_opts_std, include=FALSE}
# ---- R_Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)

old_digits <- getOption("digits")
options(digits = 2)
```

```{r r_misc_std, include=FALSE}
loadfonts("win")

my_blue   <- "#0059B3"
my_orange <- "#B35A00"
my_pink   <- "#B30059"
my_green  <- "#59B300"
```

<!-- Extra setup -->

```{r setup_lib_extra, include=FALSE}
library(sf)
library(httr)
library(magick)
library(geojsonio)
```

```{r map_conversion, include=FALSE, eval=FALSE}
# Load map
load("~/R/misc/maps/states_map_simp.RData")

states_48 <- states_map_simp %>%
  filter(NAME %in% c(state.name, "District of Columbia")) %>%
  filter(!(NAME %in% c("Alaska", "Hawaii"))) %>%
  filter(TYPE != "Water")

# Dissolved USA map
usa_map <- states_48 %>%
  st_union() %>%
  st_transform(4269) %>%
  st_set_crs(4269)

# usa_map <- tibble(thing = "Others",
#                   display_name = "Other US Basins",
#                   value = this_week[this_week$basin == "Others", ]$value,
#                   change_1wk = this_week[this_week$basin == "Others", ]$change_1wk,
#                   geometry = st_geometry(usa_map)) %>%
#   st_sf() %>%
#   st_transform(4269) %>%
#   st_set_crs(4269)

## Basins map
basins_map <- sf_plays_total %>%
  # select(Shale_play, value, change_1wk, geometry) %>%
  select(Shale_play, geometry) %>%
  rename(thing = Shale_play) %>%
  st_transform(4269) %>%
  st_set_crs(4269)

basins_map[8, ]$geometry <- st_geometry(st_union(basins_map[8, ],
                                                 basins_map[8, ]))

basins_map$display_name <- basins_map$thing

## USA map with holes, then filled with basins

new_usa_map <- usa_map %>%
  st_difference(st_union(basins_map))

newest_map <- basins_map %>%
  rbind(new_usa_map)

geojson_write(st_transform(newest_map, 4269), file = "C:/Users/Luke/D3/data/geo_newest_map.json")
```
