---
title  : "US Rig Counts"
author : "Luke Smith"
date   : "2017-10-06"
tags   : [r, oil, gas, oil and gas, rig counts]
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : "US Rig Counts"
  description : ""
  image       : ""
og :
  image : ""
---


```{r setup_lib_std, include=FALSE}
# ---- Library_Tidyverse_Setup
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)

# ---- My_Blogging_Setup
library(blg)
```

```{r knitr_opts_chunk_std, include=FALSE}
# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r knitr_opts_hooks_std, include=FALSE}
# ---- knitr_Options_Setup
orig_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")

# ---- Hooks_Setup
knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

old_inline <- knit_hooks$get("inline")
```

```{r r_opts_std, include=FALSE}
# ---- R_Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)

old_digits <- getOption("digits")
options(digits = 2)
```

```{r r_misc_std, include=FALSE}
loadfonts("win")

my_blue   <- "#0059B3"
my_orange <- "#B35A00"
my_pink   <- "#B30059"
my_green  <- "#59B300"
```

<!-- Extra setup -->

```{r setup_lib_extra, include=FALSE}
library(magick)
```

```{r knitr_ops_chunk_extra, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r extract_data, include=FALSE}
load("~/R/misc/oil/price/oil_price.RData")
load("~/R/misc/oil/US/production/state_prod.RData")
load("~/R/misc/oil/US/rig_counts/rc_state.RData")
```

<!-- Begin analysis -->

```{r pre_analysis}
rm_loc <- "U\\.S\\.|\\(PADD"

mrsp <- state_prod %>%
  filter(!grepl(rm_loc, location)) %>%
  filter(date == max(date))

mrsp_number <- mrsp %>%
  arrange(desc(production)) %>%
  mutate(rnk = cut_number(production, 4L)) %>%
  select(location, rnk)

mrsp_interval <- mrsp %>%
  arrange(desc(production)) %>%
  mutate(rnk = cut_interval(production, 4L)) %>%
  select(location, rnk)

## Get rid of states with all 0's
rc_state_zeros <- rc_state %>%
    filter(location != "TOTAL US") %>%
    group_by(location) %>%
    mutate(offshore = if_else(is.na(offshore), 0L, offshore),
           land  = if_else(is.na(land), 0L, land),
           total = land + offshore) %>%
    summarize(total = sum(total, na.rm = TRUE)) %>%
    filter(total == 0)

rc_state <- rc_state %>%
    anti_join(rc_state_zeros, "location")
```

```{r plots}
## Current production bar chart
state_prod %>%
  filter(!grepl(rm_loc, location)) %>%
  filter(date == max(date)) %>%
  filter(production != 0) %>%
  ggplot(aes(reorder(location, production, identity), production)) +
  geom_col(fill = blg::clrs$green) +
  coord_flip()

## Historical production line chart
state_prod %>%
  filter(!grepl(rm_loc, location)) %>%
  filter(date >= as.Date("1981-01-01")) %>%
  ggplot(aes(date, production)) +
  geom_line(aes(group = location))

## Historical production line chart
#  ~ Faceted by cut_number()
state_prod %>%
    filter(!grepl(rm_loc, location)) %>%
    filter(date >= as.Date("1981-01-01")) %>%
    left_join(mrsp_number, "location") %>%
    ggplot(aes(date, production)) +
    geom_line(aes(group = location)) +
    facet_wrap(~rnk, scales = "free_y")

#  ~ Faceted by cut_interval()
state_prod %>%
    filter(!grepl(rm_loc, location)) %>%
    filter(date >= as.Date("1981-01-01")) %>%
    left_join(mrsp_interval, "location") %>%
    ggplot(aes(date, production)) +
    geom_line(aes(group = location)) +
    facet_wrap(~rnk, scales = "free_y")

## production ~ land
#  ~ For Texas
rc_state %>%
    mutate(location = case_when(
        location == "N. Dakota" ~ "North Dakota",
        TRUE ~ location
    )) %>%
    filter(location == "Texas") %>%
    mutate(ym = zoo::as.yearmon(date)) %>%
    left_join(state_prod %>%
                  filter(location == "Texas") %>%
                  mutate(ym = zoo::as.yearmon(date)) %>%
                  select(-date),
              c("location", "ym")) %>%
    ggplot(aes(land, production)) +
    geom_point()

## price ~ total
#  ~ Faceted by location
rc_state %>%
    filter(location != "TOTAL US") %>%
    group_by(location) %>%
    mutate(offshore = if_else(is.na(offshore), 0L, offshore),
           total = land + offshore) %>%
    ungroup() %>%
    left_join(oil_price, "date") %>%
    ggplot(aes(total, price)) +
    geom_point(aes(group = location), alpha = 1/4) +
    facet_wrap(~location, scales = "free")
```

```{r animation, eval=FALSE}
## price ~ total
#  ~ Faceted by location
#  ~ animated

ani_pred <- rc_state %>%
    filter(location != "TOTAL US") %>%
    group_by(location) %>%
    mutate(offshore = if_else(is.na(offshore), 0L, offshore),
           total = land + offshore) %>%
    summarise(n = n()) %>%
    distinct(n)

if (nrow(ani_pred) == 1) {
  
  # Set data
  dat <- rc_state %>%
    filter(location != "TOTAL US") %>%
    group_by(location) %>%
    mutate(offshore = if_else(is.na(offshore), 0L, offshore),
           total = land + offshore) %>%
    ungroup() %>%
    left_join(oil_price, "date")
  
  # Set iterators
  it_loc <- dat %>% distinct(location) %>% pull(location)
  it_loc <- it_loc %>% rep(4) %>% sort()
  it_num <- seq_along(it_loc)
  
  # Set directory to dump data
  td <- tempdir()
  
  img <- it_loc %>%
    map2_chr(it_num, ~{
      gg <- ggplot(filter(dat, location == .x), aes(total, price)) +
        geom_smooth(method = "lm", color = clrs$blue, se = FALSE) +
        geom_point(aes(group = location), alpha = 1/5) +
        labs(title = paste0("Rig Count and Oil Price Trends Per State"),
             subtitle = paste0("State: ", .x, "\n"),
             x = "Rig Count",
             y = "Oil Price ($)")
      
      fil <- file.path(td, sprintf("%s.png", as.character(.y)))
      ggsave(fil, gg, , units = "in", width=6, height=3.5)
      fil
    }) %>%
    map(image_read) %>%
    map(image_scale, geometry = "675x") %>%
    image_join()
  
  img %>%
    image_morph(4) %>%
    image_animate(10) %>%
    image_write("state_rig_count_vs_price2.gif")
}
```

<!-- Clean up all the sensitive stuff -->

```{r cleanup, include=FALSE}
rm(list = ls(pattern = "api_key_"))
```
